import "./Welcome"
import "../../src/components/App/stories"
import "../../src/components/Counter/stories"
import "../../src/components/Container/stories"
import "../../src/components/ContactListItem/stories"
import "../../src/components/ContactThumbnail/stories"
import "../../src/components/DetailListItem/stories"
